name: Maybe Finance
description: >-
  Maybe Finance is a personal finance management application that helps you
  track your expenses, income, and investments.
slug: maybe_finance
init: false
arch:
  - aarch64
  - amd64
  - armv7
startup: application
boot: auto

ports:
  3000/tcp: 3001
map:
  - "data:rw"
build:
  dockerfile: Dockerfile
  args:
    BUILD_ARCH: "{arch}"
version: 0.3.0
environment:
  DB_HOST: "172.30.32.1" # Home Assistant's default gateway IP
  DB_PORT: "5432"
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: homeassistant # Default password from Postgres addon
  SECRET_KEY_BASE: "TEST"
  SELF_HOSTED: "true"
  DISABLE_SSL: "false"
  HOSTING_PLATFORM: "localhost"
