name: "Maybe Finance"
description: "Maybe Finance is a personal finance management application that helps you track your expenses, income, and investments."
slug: "maybe_finance"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
options:
  postgres_host: "addon_core_postgresql"
  postgres_user: maybe_user
  postgres_password: maybe_password
  postgres_db: maybe_db
schema:
  postgres_host: str
  postgres_user: str
  postgres_password: str
  postgres_db: str
ports:
  3000/tcp: 3001
environment:
  POSTGRES_HOST: "{options.postgres_host}"
  POSTGRES_USER: "{options.postgres_user}"
  POSTGRES_PASSWORD: "{options.postgres_password}"
  POSTGRES_DB: "{options.postgres_db}"
map:
  - "data:rw"
image: ghcr.io/maybe-finance/maybe
version: 0.3.0
