name: Maybe Finance
description: >-
  Maybe Finance is a personal finance management application that helps you
  track your expenses, income, and investments.
slug: maybe_finance
init: false
arch:
  - aarch64
  - amd64
  - armv7
startup: application
boot: auto
ports:
  3001/tcp: 3001
map:
  - "data:rw"
build:
  dockerfile: Dockerfile
  args:
    BUILD_ARCH: "{arch}"
version: 0.3.0
# Environment variables set here are passed to the container at runtime
environment:
  DB_HOST: "172.30.32.1"
  DB_PORT: "5432"
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: homeassistant
  SECRET_KEY_BASE: "generate_a_secure_key_here"
  SELF_HOSTED: "true"
  DISABLE_SSL: "false"
  HOSTING_PLATFORM: "localhost"
