name: "Publish"
on:
  release:
    types: [published]

jobs:
  publish:
    name: Build and Push to GHCR
    strategy:
      fail-fast: false
      matrix:
        architecture: [amd64, aarch64]
    runs-on: ${{ (matrix.architecture == 'amd64' && 'ubuntu-latest') || (matrix.architecture == 'aarch64' && 'ubuntu-22.04-arm') }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Version from Config
        id: extract_version
        run: |
          VERSION=$(grep '^version:' maybe_finance/config.yaml | awk '{print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.MAYBE_HASS_RELEASE }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image
        run: |
          cd maybe_finance
          IMAGE_NAME=ghcr.io/m123-dev/${{ matrix.architecture }}-maybe_finance_homeassistant
          VERSION=${{ env.VERSION }}

          docker buildx build \
            --platform linux/${{ matrix.architecture }} \
            --build-arg BUILD_ARCH=${{ matrix.architecture }} \
            -t $IMAGE_NAME:$VERSION \
            -t $IMAGE_NAME:latest \
            --push

      - name: Logout from GitHub Container Registry
        run: |
          docker logout ghcr.io
