name: "Publish"

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, aarch64]
        #i386
        #armv7,
        #armhf,
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Login to the Github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.MAYBE_HASS_RELEASE }}

      - name: Build & Publish
        uses: home-assistant/builder@master
        with:
          args: |
            --${{ matrix.architecture }} \
            --target maybe_finance \
            --docker-hub "ghcr.io/${{ github.repository_owner }}"
