name: "Publish"

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Login to the Github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.MAYBE_HASS_RELEASE }}
        #  username: ${{ secrets.DOCKERHUB_USERNAME }}
        #  password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Publish
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target maybe_finance \
            --docker-hub "ghcr.io/${{ github.repository_owner }}" \
#            --docker-hub m123ist