name: "Test Build"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-build:
    name: Test Build
    strategy:
      fail-fast: false
      matrix:
        architecture: [amd64, aarch64]
    runs-on: ${{ (matrix.architecture == 'amd64' && 'ubuntu-latest') || (matrix.architecture == 'aarch64' && 'ubuntu-22.04-arm') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image (test only)
        run: |
          cd maybe_finance
          IMAGE_NAME=ghcr.io/m123-dev/${{ matrix.architecture }}-maybe_finance_homeassistant
          CACHE_IMAGE=ghcr.io/m123-dev/cache-${{ matrix.architecture }}-maybe_finance_homeassistant

          docker buildx build \
            --platform linux/${{ matrix.architecture }} \
            --build-arg BUILD_ARCH=${{ matrix.architecture }} \
            -f Dockerfile .

#             --cache-from=type=registry,ref=$CACHE_IMAGE \
#--cache-to=type=registry,ref=$CACHE_IMAGE,mode=max \
