name: "Test"

on: [pull_request]

jobs:
  build:
    name: Test build (${{ matrix.arch }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Prevents cancellation of remaining jobs if one fails
      matrix:
        arch: [amd64, aarch64]
        #armv7,
        #i386
        #armhf,
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Test build
        uses: home-assistant/builder@master
        with:
          args: |
            --test \
            --${{ matrix.arch }} \
            --target maybe_finance \
            --docker-hub "ghcr.io/${{ github.repository_owner }}" \

